### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by nattyluke** [apertureless/vue-cookie-law#43]
### vue & vue-cookie-law version
2.0.x, x.y.z

### Steps to reproduce

1. npm -i vue-cookie-law 
2. in app: 
import CookieLaw from 'vue-cookie-law'
and added to components

### What is Expected?
It should work
### What is actually happening?
Compiling gives an error:
Error: Cannot find module '!!../../node_modules/css-loader/index.js?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-863fd97e","scoped":false,"hasInlineConfig":false}!../../node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./CookieLaw.vue' from '/home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/vue-cookie-law/dist'
    at /home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/lukas/Dokumente/cms2web/browserify/lmediamanager/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47

Never had that problem, what am i doing wrong?

**Comment by apertureless** [comment]
Hey, are you using webpack ? If so, which version?

**Comment by nattyluke** [comment]
No, i'm using "browserify": "^13.0.1"
